### ISSUE TITLE
[Improvement] Missing Eagle Libs

### ISSUE THREAD

**Issue by StoneColdCrazy** [skaman82/Pocket-Groundstation#12]
Hi, i take a closer look on youre eagle files and habe missing libs. (I plan to build and test it with an rapidFire Module, maybe the sync for the osd is cleaner ;) )

But Eagle is missing some custom libs:
> PCB 1D -> Arduino-clone / FPVTools
> PCB 2D -> diy-modules

Can you upload them also? 
Makes it easyer to stay in sync

**Comment by skaman82** [comment]
@StoneColdCrazy you don't need the EAGLE libs - i provided the gerber files as well for ordering the pcbs (but I upload them anyway :D) EDIT: some of the original libs you mentioned needed some tweaks

**Comment by skaman82** [comment]
BTW. Rapidfire will not help with the sync issues

**Comment by skaman82** [comment]
Uploaded

**Comment by StoneColdCrazy** [comment]
Thank you, maybe i want to change some of your layouts, so it was better to have the missing libs...
