### ISSUE TITLE
DVR control in the OLED menu system

### ISSUE THREAD

**Issue by skaman82** [skaman82/Pocket-Groundstation#4]

**Comment by skaman82** [comment]
Menu structure
![bildschirmfoto 2018-06-04 um 13 25 14](https://user-images.githubusercontent.com/11768024/41067600-87351a94-69e6-11e8-9814-b60aa7273974.png)

**Comment by skaman82** [comment]
some graphics
![menu](https://user-images.githubusercontent.com/11768024/41067664-b3284900-69e6-11e8-8b21-a21326d3aabd.png)

**Comment by skaman82** [comment]
@tavdog I've heard that you'd like to join our little project. Feel free to add some code any time :)

**Comment by tavdog** [comment]
alright, lemme just do a little git refresher and I'll try to contribute.

**Comment by skaman82** [comment]
@tavdog great!

**Comment by skaman82** [comment]
done!
