### ISSUE TITLE
Add DockKing serial protocol

### ISSUE THREAD

**Issue by skaman82** [skaman82/Pocket-Groundstation#6]

**Comment by Philip-Mohr** [comment]
![uart](https://user-images.githubusercontent.com/9449243/40987912-12f58f3a-68ea-11e8-8065-0333a8fe0483.jpg)

**Comment by NightHawk32** [comment]
First implementation is done but testing it with real hardware needs to be done. Since it uses Softserial of the OSD the hardware serial port can be used for debugging by using some serial prints.

**Comment by skaman82** [comment]
thanks @NightHawk32 !
